"use clinet";

import Header from "@/components/Header";
import Player from "@/components/Player";
import SidebarNav from "@/components/SidebarNav";
import { Providers } from "@/store/provider";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Providers>
          <div className="flex flex-row justify-start">
            <SidebarNav />
            <div className="flex-1 p-4 text-white">
              <Header />
              {children}
              <Player />
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
